### ISSUE TITLE
Migrate to GitHub Actions?

### ISSUE THREAD

**Issue by rgl** [libgit2/libgit2sharp.nativebinaries#116]
The current CI pipeline is somewhat complex due the use of two different CI services, travis and appveyor, and a [final script to merge everything into a single nuget package](https://github.com/libgit2/libgit2sharp.nativebinaries/blob/master/download.build.artifacts.and.package.ps1) (which it seems has to be manually executed by whoever is doing the final release).

Can this be unified in a single GitHub Actions pipeline/workflow?

**Comment by bording** [comment]
Fixed in #121
