### ISSUE TITLE
macOS Arm64 - any time soon?

### ISSUE THREAD

**Issue by arturcic** [libgit2/libgit2sharp.nativebinaries#129]
Do you know if the macOS Arm64 version is anytime soon available?

**Comment by bording** [comment]
In theory it should be possible to add this. There just needs to be some work in the build scripts and CI workflows to make it happen.

**Comment by arturcic** [comment]
same for alpine on Arm64 I suppose right?

**Comment by bording** [comment]
Yes, though I'm not sure how to create an alpine docker image that will enable cross compilation for arm/arm64.
