### ISSUE TITLE
2.0.315 package includes libgit2_tests.exe

### ISSUE THREAD

**Issue by AArnott** [libgit2/libgit2sharp.nativebinaries#139]
Next to the `runtimes\win-x86\native\git2-182d0d1.dll` file is a `libgit2_tests.exe` file that is both large and likely unnecessary to using libgit2sharp.

This is in 2.0.315. It did not appear in 2.0.315-alpha.0.9.

**Comment by bording** [comment]
Hmm, interesting. Not sure how that happened. Definitely not intentional.

**Comment by bording** [comment]
2.0.316 and newer didn't have this problem, so I'm still not sure how those snuck in for 2.0.315. Going to close this and keep an eye on any new packages to make sure it doesn't happen again.
