### ISSUE TITLE
LibGit2Sharp.NativeBinaries and LibGit2Sharp

### ISSUE THREAD

**Issue by rozeboosje** [libgit2/libgit2sharp.nativebinaries#153]
Ladies and gents,

If you're going to issue a new version of LibGit2Sharp.NativeBinaries to NuGet, can you please issue a corresponding release of LibGit2Sharp? It's pretty pointless to get build 2.0.321 of the Native Binaries only to find that LibGit2Sharp 0.28.0 can't use it.

.NET Project for .NET Framework 4.8

**Comment by rozeboosje** [comment]
Thanks @bording 

Okay... I removed our reference to NuGet package LibGit2Sharp.NativeBinaries

I checked the build output and I see LibGit2Sharp.NativeBinaries is no longer included in the bin folder

Our packages are included as PackageReferences - at least in the one project in which we used LibGit2Sharp

It all seems to work fine now. So maybe I should just shrug and go "alright then". But I'm curious though. When I look at NuGet I see under Dependencies that it is dependent on LibGit2Sharp.NativeBinaries build 2.0.320

This DLL is not present in the output, so how is it possible that it still works fine? Mind you, I'm not complaining, but I'm confused....

**Comment by bording** [comment]
> I checked the build output and I see LibGit2Sharp.NativeBinaries is no longer included in the bin folder

What exactly are you looking for/expecting to see when you looked at the build output here?

For a .NET Framework project, the NativeBinaries package should be resulting in a lib folder being copied into the bin folder of the project.

**Comment by rozeboosje** [comment]
Yup that does the job.

**Comment by rozeboosje** [comment]
Thanks @bording  - yes I hadn't accounted for that lib folder that includes a git2_.....dll

Also, today there was a new NuGet package for LibGit2Sharp - 0.29.0 - and after I figured out that CloneOptions.CredentialsProvider was now in CloneOptions.FetchOptions.CredentialsProvider everything built and runs successfully. Cheers.

**Comment by rozeboosje** [comment]
Thanks again
