### ISSUE TITLE
NuGet package broken for xbuild builds

### ISSUE THREAD

**Issue by ermshiperete** [libgit2/libgit2sharp.nativebinaries#25]
When using the libgit2sharp.nativebinaries package on Linux/Mono the files don't get copied over to the output directory because xbuild currently doesn't honor imported ItemGroups.

I think it would be better to use a target instead of the properties.

**Comment by bording** [comment]
Where are you seeing this behavior? LibGit2Sharp itself uses the nativebinaries package, and the Travis CI builds use xbuild and everything works correctly there.

**Comment by ermshiperete** [comment]
Oops, sorry. Now I feel stupid. Yes, it works completely fine, and it's the build script in GitVersion that copies only part of the files. I really shouldn't submit bugs or PRs when I'm not completely awake :smile:
