### ISSUE TITLE
Under Which Open Source License Is This Released? 

### ISSUE THREAD

**Issue by mesheets** [libgit2/libgit2sharp.nativebinaries#42]
The GitHub project page indicates that libgit2sharp.nativebinaries is released under the MIT license.
 - https://github.com/libgit2/libgit2sharp.nativebinaries
 - https://github.com/libgit2/libgit2sharp.nativebinaries/blob/master/LICENSE.md

However, the license bundled with the corresponding NuGet packages states that the license is GNU GPL 2.
 - https://github.com/libgit2/libgit2sharp.nativebinaries/blob/master/nuget.package/NativeBinaries.nuspec
 - https://github.com/libgit2/libgit2sharp.nativebinaries/blob/master/LICENSE.md
 - https://www.nuget.org/packages/LibGit2Sharp.NativeBinaries/ (click the "Licensing" link, which redirects to the above link)

Sonatype scans are detecting the license as GPL 2.0 and not the MIT license that is listed on the project home page.

Thank you!

**Comment by ethomson** [comment]
_This project_, the source code contained in this repository, is MIT licensed.

The point of this project is to build libgit2, which is GPL2 with a linking exception.  Thus the results that are produced (libgit2) are under its license.
