### ISSUE TITLE
Nuget package not working on Ubuntu 19.04

### ISSUE THREAD

**Issue by rose-a** [libgit2/libgit2sharp.nativebinaries#98]
The nuget package as a dependency does not work on Ubuntu 19.04 (see https://github.com/GitTools/GitVersion/issues/1744).

Im not shure which binaries it tries tu use, I'd suspect it selects the `linux-x64` binaries (the error looks very similar to the one in https://github.com/GitTools/GitVersion/issues/1510).

When built and installed directly on the machine, everything works fine.

**Comment by dnperfors** [comment]
Same happens on Ubuntu 20.04, it definitely tries to use `linux-x64` which rely on libssl 1.0, instead of 1.1

**Comment by ethomson** [comment]
libssl is no longer a dependency for the LibGit2Sharp builds, thanks to https://github.com/libgit2/libgit2sharp/pull/1618.  Upgrading to the latest nuget package will fix this. https://www.nuget.org/packages/LibGit2Sharp/0.27.0-preview-0096
